apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nibblers.trahey.us
spec:
  scope: Namespaced
  group: trahey.us
  names:
    kind: Nibbler
    plural: nibblers
    singular: nibbler
    shortNames:
      - nib
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                initImage:
                  type: string
                workerImage:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true