---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "nibbler-operator"
  name: nibbler-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nibbler-operator
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [trahey.us]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: ["apps", ""]
    resources: [deployments, services]
    verbs: [create, list, get, watch, update, patch, delete]
  # Application: read-only access for watching cluster-wide.
  - apiGroups: [trahey.us]
    resources: [nibblers]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nibbler-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nibbler-operator
subjects:
  - kind: ServiceAccount
    name: nibbler-operator
    namespace: "nibbler-operator"
