apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc.yaml
- service.yaml
- deployment.yaml


generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: mysql-db-user
  files: 
    - .mysql_user.txt
    - .mysql_pass.txt
configMapGenerator:
- name: schema
  files:
  - schema.sql